name: Auth.Api
on:
  push:
    branches:
      - dev
    paths:
      - Auth.Api/**
      - .github/workflows/Auth.Api.yaml
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Auth.Api.Test
    env:
      CONFIGURATION: Release
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      SOLUTION_PATH: Auth.Api/Auth.Api.sln
      SERVICE_NAME: authapi
      SERVICE_SOURCE: Auth.Api/Auth.Api
    steps:
      - uses: actions/checkout@v3
      - run: 'dotnet build ${{ env.SOLUTION_PATH }} -c ${{ env.CONFIGURATION }}'
      - run: 'dotnet test ${{ env.SOLUTION_PATH }} -c ${{ env.CONFIGURATION }} --no-build --no-restore'
      - name: 'google auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'deploy to google cloud run'
        run: 'gcloud run deploy ${{ env.SERVICE_NAME }} --source . --region=us-east1'
        working-directory: ${{ env.SERVICE_SOURCE }}