name: Auth.Api
on:
  push:
    branches:
      - main
    paths:
      - Auth.Api/**
      - .github/workflows/Auth.Api.yaml
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      DOCKERFILE_DIRECTORY: Auth.Api/Auth.Api
      SOLUTION_PATH: Auth.Api/Auth.Api.sln
    steps:
      - uses: actions/checkout@v3
      - run: 'dotnet build ${{ env.SOLUTION_PATH }} -c ${{ env.CONFIGURATION }}'
      - run: 'dotnet test ${{ env.SOLUTION_PATH }} -c ${{ env.CONFIGURATION }} --no-build --no-restore'
      - run: 'docker build -f Dockerfile .'
        working-directory: ${{ env.DOCKERFILE_DIRECTORY }}
  